---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f ./local.yml run --rm backend sh -c "python manage.py test"
      - name: Lint
        run: docker-compose -f ./local.yml run --rm backend sh -c "flake8"